# -*- coding: utf-8 -*-
"""PARRENO Custom App that uses the OpenAI Platform API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H1XsmTAwx3iMMHIyDfgjZM-TpI7siWLC

#Text to Color Generator
##Submitted by: Rey Matthew G. Parreño - BSCS 3A
"""

!pip install openai

# Commented out IPython magic to ensure Python compatibility.
# %env OPEN_AI_KEY=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

import openai
import random

openai.api_key = "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"

def text_to_color(description):
    prompt = f"Convert the following text description to a color: {description}\nColor:"
    completions = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=1,
        n=1,
        stop=None,
        temperature=0.5,
    )

    response = completions.choices[0].text.strip()
    return response

description = input("Enter a text description: ")
color = text_to_color(description)
print(f"The color for '{description}' is {color}.")